#!/usr/bin/groovy

properties([
  parameters([
    string(defaultValue: "devnet-development", description: 'Branch / commit:', name: 'BRANCH'),
    string(defaultValue: "devnet", description: 'Tag (devnet, devnet1, ...)', name: 'TAG'),
    booleanParam(defaultValue: false, description: 'Append the commit SHA', name: 'COMMITSHA'),
    booleanParam(defaultValue: true, description: 'Use cache (faster)', name: 'USE_CACHE'),
   ])
])
pipeline{
    agent {
        node {
            label 'lisk-docker'
            customWorkspace "workspace/${URLDecoder.decode(JOB_NAME)}/${BUILD_NUMBER}"
        }
    }
    stages {
        stage('Load library') {
            steps {
                library 'lisk-jenkins'
            }
        }
        stage('Build release') {
            steps {
                script {
                    def cache_file = ''
                    def buildEnv = dir('docker/lisk-build'){
                        return docker.build('lisk-build')
                    }
                    buildEnv.inside("-v $HOME/cache:$HOME/cache") {
                        dir('lisk'){
                            checkout([$class: 'GitSCM', branches: [[name: "${params.BRANCH}" ]],
                                userRemoteConfigs: [[url: 'https://github.com/LiskHQ/lisk']]])
                            if ( params.USE_CACHE ) {
                                cache_file = restoreCache("package.json")
                            }
                            sh """
                            npm install
                            node ./node_modules/.bin/grunt release
                            jq -r '.version' package.json > ".lisk-version"
                            git rev-parse --short HEAD > .git/commit-id
                            """
                            if ( params.USE_CACHE ) {
                                saveCache(cache_file, './node_modules', 7)
                            }
                        }
                        env.COMMIT = readFile("lisk/.git/commit-id").trim()
                        env.VERSION = readFile("lisk/.lisk-version").trim()
                        dir('lisk-build'){
                            git url: 'https://github.com/LiskHQ/lisk-build', branch: '1.1.0'
                            if ( params.USE_CACHE ) {
                                cache_file = restoreCache("config.sh")
                            }
                            sh """
                            cp ../lisk/release/lisk-${env.VERSION}.tgz src/
                            bash build.sh -n dev -v "${env.VERSION}"
                            """
                            if ( params.USE_CACHE ) {
                                saveCache(cache_file, './src', 14, 'lisk-*')
                            }
                        }
                    }
                }
            }
        }
        stage('Upload tarball'){
            steps {
                script {
                    def outputFile = params.COMMITSHA ? "lisk-${env.VERSION}-${env.COMMIT}-Linux-x86_64.tar.gz" : "lisk-${env.VERSION}-Linux-x86_64.tar.gz"
                    dir("lisk-build") {
                        sh """
                        if [ ! -f release/${outputFile} ]; then
                            cd release
                            tar xzf lisk-${env.VERSION}-Linux-x86_64.tar.gz
                            mv lisk-${env.VERSION}-Linux-x86_64 lisk-${env.VERSION}-${env.COMMIT}-Linux-x86_64
                            tar czf ${outputFile} lisk-${env.VERSION}-${env.COMMIT}-Linux-x86_64
                            sha256sum ${outputFile} > ${outputFile}.SHA256
                            cd ..
                        fi
                        s3cmd put --acl-public release/${outputFile} s3:///lisk-releases/lisk-core/${params.TAG}/${outputFile}
                        s3cmd put --acl-public release/${outputFile}.SHA256 s3:///lisk-releases/lisk-core/${params.TAG}/${outputFile}.SHA256
                        """
                    }
                }
            }
        }
        stage('Clean WS') {
            steps {
                cleanWs()
            }
        }
    }
}
